### ISSUE TITLE
HerokuのCIツールについての調査

### ISSUE THREAD

**Issue by bake0937** [pepabo-college/migacode#26]
## 概要
HerokuのCIツール導入についての調査をします

## クローズ条件
HerokuのCIツール導入方法が分かりWIPプルリクに必要な手順をTODOとして記載できること。

**Comment by bake0937** [comment]
- AddonのCodeShipを導入すればokであることがわかりました。
  - https://documentation.codeship.com/basic/continuous-deployment/deployment-to-heroku/
  - http://qiita.com/u651601f/items/8da10ca147be241318b3

**Comment by bake0937** [comment]
## TODO
- [x] Herokuアプリにcodeshipをインストール
  https://elements.heroku.com/addons/codeship
- [x] デモ終了後にCodeShipのアドオンを外す(6/30作業済み)
  - Heroku側
    - [x] Heroku Addon の「CodeShip」を削除
  - GitHub側
    - [x] [Authorized OAuth Apps](https://github.com/settings/applications?page=1)からCodeShipを選択し、「Revoke」を選択
    - [x] [Deploy keys](https://github.com/pepabo-college/migacode/settings/keys)からCodeShipを削除
